name:                advent2020
version:             0.1.0.0
github:              "lawrencetaylor/advent2020"
license:             BSD3
author:              "Lawrence Taylor"
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lawrencetaylor/advent2020#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers

library:
  source-dirs: src